- name: F5 TLS automation
  hosts: bigip_group
  connection: local
  gather_facts: false
  serial: 1

  vars:
    provider:
      server: 'bigip.hostname'
      user: 'admin'
      password: 'bigip_admin_password'
      validate_certs: no
      server_port: 443
    partition: 'Common'
    state: 'present'

  roles:
    - roles/f5cs_dns_letsencrypt_bigip
