---

# Created by - Jon Calalang
# This task comes with no warrenty or support
# There was no call out for creating a SSL cert and Key, there are modules for this called bigip_ssl_key and bigip_ssl_certificate
# Modules used:
#
# bigip_profile_server_ssl
# bigip_monitor_https
# bigip_pool
# bigip_pool_member - ***NOTE*** When creating a new pool member, one of either address or fqdn must be provided. This parameter cannot be updated after it is set.
# bigip_virtual_server
#
# Module Documentation: https://docs.ansible.com/ansible/2.9/modules/list_of_all_modules.html
#
#

- name: Create a VIP, pool and pool members
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    provider:
      server: fqdn.bigip.com
      user: admin
      password: password
      validate_certs: no
      server_port: 443
    partition: "Common"
    application_name: ""
    state: "present"

  tasks:
    - name: Create a server SSL profile with a cert/key/chain setting
      bigip_profile_server_ssl:
        provider: "{{ provider }}"
        partition: "{{ partition }}"
        name: "tls_profile_{{application_name}}"
        state: "{{ state }}"
        certificate: /Common/default.crt
        key: /Common/default.key
        chain: /Common/default.crt
      delegate_to: localhost

    - name: Create HTTPS Monitor
      bigip_monitor_https:
        provider: "{{ provider }}"
        partition: "{{ partition }}"
        name: "https_monitor_{{application_name}}"
        state: "{{ state }}"
        description: "https_monitor_{{application_name}}"
        send: GET /health\r\n
        ssl_profile: "/{{ partition }}/tls_profile_{{application_name}}"
        receive: "UP"
        receive_disable: "none"
        interval: "10"
        time_until_up: "0"
        timeout: "31"
      delegate_to: localhost

    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        partition: "{{ partition }}"
        name: "pool_{{application_name}}"
        state: "{{ state }}"
        description: "pool_{{application_name}}"
        monitors:
         - "/{{ partition }}/https_monitor_{{application_name}}"
        lb_method: least-connections-member
        slow_ramp_time: 120
      delegate_to: localhost

    - name: Add pool members aggregate, remove non aggregates
      bigip_pool_member:
        provider: "{{ provider }}"
        partition: "{{ partition }}"
        pool: "pool_{{application_name}}""
        replace_all_with: yes
        reuse_nodes: no
        members:
          - ip: 172.16.246.161
            partition: "{{ partition }}"
            port: 9014
            description: "pool_member_1"
          - ip: 172.16.246.194
            partition: "{{ partition }}"
            port: 9014
            description: "pool_member_2"
          - hostname: www.nginx.com
            partition: "{{ partition }}"
            port: 80
            description: "web server dummy"
      delegate_to: localhost

    - name: Create a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        partition: "{{ partition }}"
        name: "virtual_{{application_name}}"
        state: "{{ state }}"
        description: "virtual_{{application_name}}"
        destination: 192.168.6.175
        pool: "pool_{{application_name}}"
        port: "9014"
        snat: Automap
        profiles:
          - tcp
      delegate_to: localhost
