---

- include_tasks: prepare_environment.yml

- name: check if certificate exists, if exist then do not create the same cert/key pair
  stat:
    path: "{{ letsencrypt_certs_dir }}/{{ domain_name }}.crt"
  register: cert_exist_result

- include_tasks: initial_letsencrypt_request.yml
  when: not cert_exist_result.stat.exists

- include_tasks: mod_acme_record.yml
  when: not cert_exist_result.stat.exists

- include_tasks: finish_letsencrypt_request.yml
  when: not cert_exist_result.stat.exists

- include_tasks: send_cert_to_bigip.yml
