---

#    Created by - Jon Calalang
#    This task comes with no warrenty or support
#    Modules used:
#
#    get_url
#    bigip_profile_client_ssl
#    ansible.builtin.file
#
#    Module Documentation: https://docs.ansible.com/ansible/2.9/modules/list_of_all_modules.html
#
#    Use for Basic Auth
#    - name: < Fetch file that requires authentication.
#            username/password only available since 2.8, in older versions you need to use url_username/url_password
#      get_url:
#        url: http://example.com/path/file.conf
#        dest: /etc/foo.conf
#        username: bar
#        password: '{{ mysecret }}'

- name: Copy Certificate and Key from URL create BIG-IP Server SSL Profile
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    provider:
      server: 'fqdn.bigip.com'
      user: 'username'
      password: 'password'
      validate_certs: no
      server_port: 443
    partition: 'Common'
    application_name: 'bigip_example_application'
    state: 'present'
    certurl: 'https://example.f5.com/chain.crt'
    cachainurl: 'https://example.f5.com/chain.crt'
    keyurl: 'https://example.f5.com/default.key'

  tasks:

    - name: Download Key
      get_url:
        url: '{{ keyurl }}'
        dest: '{{ playbook_dir }}/{{ application_name }}.key'

    - name: Download Certificate
      get_url:
        url: '{{ certurl }}'
        dest: '{{ playbook_dir }}/{{ application_name }}.crt'

    - name: Download CA Chain
      get_url:
        url: '{{ cachainurl }}'
        dest: '{{ playbook_dir }}/{{ application_name }}_cachain.crt'

    - name: Use a file lookup to import Key
      bigip_ssl_key:
        provider: '{{ provider }}'
        partition: '{{ partition }}'
        name: '{{ application_name}}_bundle'
        state: '{{ state }}'
        content: "{{ lookup('file', '{{ playbook_dir }}/{{ application_name }}.key') }}"
      delegate_to: localhost

    - name: Use a file lookup to import Certificate
      bigip_ssl_certificate:
        provider: '{{ provider }}'
        partition: '{{ partition }}'
        name: '{{ application_name}}_bundle'
        state: '{{ state }}'
        content: "{{ lookup('file', '{{ playbook_dir }}/{{ application_name }}.crt') }}"
      delegate_to: localhost

    - name: Use a file lookup to import CA Chain
      bigip_ssl_certificate:
        provider: '{{ provider }}'
        partition: '{{ partition }}'
        name: '{{ application_name}}_cachain'
        state: '{{ state }}'
        content: "{{ lookup('file', '{{ playbook_dir }}/{{ application_name }}_cachain.crt') }}"
      delegate_to: localhost

    - name: Create a client SSL profile with a cert/key/chain setting
      bigip_profile_client_ssl:
        provider: '{{ provider }}'
        partition: '{{ partition }}'
        name: 'tls_profile_{{application_name}}'
        state: '{{ state }}'
        cert_key_chain:
          - cert: '/{{ partition }}/{{ application_name}}_bundle'
            key: '/{{ partition }}/{{ application_name}}_bundle'
            chain: '/{{ partition}}/{{ application_name}}_cachain'
      delegate_to: localhost

    - name: Remove Key
      ansible.builtin.file:
        path: '{{ playbook_dir }}/{{ application_name }}.key'
        state: absent

    - name: Remove Certificate
      ansible.builtin.file:
        path: '{{ playbook_dir }}/{{ application_name }}.crt'
        state: absent

    - name: Remove CA Chain
      ansible.builtin.file:
        path: '{{ playbook_dir }}/{{ application_name }}_cachain.crt'
        state: absent
