---

#    Created by - Jon Calalang
#    This task comes with no warrenty or support
#    Modules used:
#
#    get_url
#    bigip_profile_server_ssl
#    ansible.builtin.file
#
#    Module Documentation: https://docs.ansible.com/ansible/2.9/modules/list_of_all_modules.html
#

- name: Copy Certificate and Key from Venafi create BIG-IP Server SSL Profile
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    provider:
      server: 'fqdn.bigip.com'
      user: 'username'
      password: 'password'
      validate_certs: no
      server_port: 443
    partition: 'Common'
    application_name: 'bigip_example_application'
    state: 'present'
    certurl: 'https://example.venafi.com/chain.crt'
    cachainurl: 'https://example.venafi.com/chain.crt'
    keyurl: 'https://example.venafi.com/default.key'
    venafiuser: 'username'
    venafipassword: 'password'

  tasks:

    - name: Download Key
      get_url:
        url: '{{ keyurl }}'
        dest: '{{ playbook_dir }}/{{ application_name }}.key'
        username: '{{ venafiuser }}'
        password: '{{ venafipassword }}'

    - name: Download Certificate
      get_url:
        url: '{{ certurl }}'
        dest: '{{ playbook_dir }}/{{ application_name }}.crt'
        username: '{{ venafiuser }}'
        password: '{{ venafipassword }}'

    - name: Download CA Chain
      get_url:
        url: '{{ cachainurl }}'
        dest: '{{ playbook_dir }}/{{ application_name }}_cachain.crt'
        username: '{{ venafiuser }}'
        password: '{{ venafipassword }}'

    - name: Use a file lookup to import Key
      bigip_ssl_key:
        provider: '{{ provider }}'
        partition: '{{ partition }}'
        name: '{{ application_name}}_bundle'
        state: '{{ state }}'
        content: "{{ lookup('file', '{{ playbook_dir }}/{{ application_name }}.key') }}"
      delegate_to: localhost

    - name: Use a file lookup to import Certificate
      bigip_ssl_certificate:
        provider: '{{ provider }}'
        partition: '{{ partition }}'
        name: '{{ application_name}}_bundle'
        state: '{{ state }}'
        content: "{{ lookup('file', '{{ playbook_dir }}/{{ application_name }}.crt') }}"
      delegate_to: localhost

    - name: Use a file lookup to import CA Chain
      bigip_ssl_certificate:
        provider: '{{ provider }}'
        partition: '{{ partition }}'
        name: '{{ application_name}}_cachain'
        state: '{{ state }}'
        content: "{{ lookup('file', '{{ playbook_dir }}/{{ application_name }}_cachain.crt') }}"
      delegate_to: localhost

    - name: Create a server SSL profile with a cert/key/chain setting
      bigip_profile_server_ssl:
        provider: '{{ provider }}'
        partition: '{{ partition }}'
        name: 'tls_profile_{{application_name}}'
        state: '{{ state }}'
        key: '/{{ partition }}/{{ application_name}}_bundle'
        certificate: '/{{ partition }}/{{ application_name}}_bundle'
        chain: '/{{ partition}}/{{ application_name}}_cachain'
      delegate_to: localhost

    - name: Remove Key
      ansible.builtin.file:
        path: '{{ playbook_dir }}/{{ application_name }}.key'
        state: absent

    - name: Remove Certificate
      ansible.builtin.file:
        path: '{{ playbook_dir }}/{{ application_name }}.crt'
        state: absent

    - name: Remove CA Chain
      ansible.builtin.file:
        path: '{{ playbook_dir }}/{{ application_name }}_cachain.crt'
        state: absent
